language: python
python:
  - "3.6"

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-set-default

before_install:
  - nvm install 6.10.3
  - nvm use 6.10.3

install:
  - pip install sphinx html5validator
  - npm install -g jshint@latest

script:
  - make test

before_deploy:
  - touch doc/_build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: doc/_build/html
  email: beheer@hisparc.nl
  name: HiSPARC-Bot
  on:
    branch: master
    python: 3.6
